apiVersion: 1

datasources:
  - name: MQTT
    type: grafana-mqtt-datasource
    uid: mqtt_local
    isDefault: true
    editable: true # Set this to true so we can inspect it in the UI
    jsonData:
      uri: tcp://mosquitto:1883
